name: KingKits
main: com.faris.kingkits.KingKits
version: ${project.version}
description: Have battles with enemies using custom made kits!
author: KingFaris10
softdepend: [ Vault ]
commands:
  kingkits:
    description: KingKits plugin command.
    usage: /kingkits [<reload|config>]
    aliases: [ "kk" ]
  pvpkit:
    description: List all the kits or choose a PvP kit!
    usage: /pvpkit [<name>|<name> <player>]
    aliases: [ "kit" ]
  createkit:
    description: Create a PvP Kit ingame with all the items in your inventory!
    usage: /createkit <name> [<guiItem>]
  deletekit:
    description: Delete a(ll) PvP kit(s).
    usage: /deletekit <*|name>
  renamekit:
    description: Rename a PvP kit.
    usage: /renamekit <name> <newname>
  createukit:
    description: Create a personal user PvP Kit ingame with all the items in your inventory!
    usage: /createukit <name> [<guiItem>]
  deleteukit:
    description: Delete a user PvP kit.
    usage: /deleteukit <name>
  renameukit:
    description: Rename a user PvP kit.
    usage: /renameukit <name> <newname>
  previewkit:
    description: Preview a kit, or make another player preview a kit.
    usage: /previewkit <kit> [<player>]
  refill:
    description: Refill bowl(s).
    usage: /refill [<all>]
    aliases: [ soup ]
